name: Lighthouse nightly
on:
  schedule:
    - cron: '0 20 * * *'   # 6am Sydney
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    env:
      URL: https://ipanemamedia.com/
      UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g @lhci/cli

      - name: Sanity check URL (must return 200)
        run: |
          code=$(curl -s -L -o /dev/null -w "%{http_code}" -A "$UA" "$URL")
          echo "HTTP $code  $URL"
          test "$code" = "200"

      - name: Create Lighthouse config
        run: |
          cat > lighthouserc.json <<JSON
          { "ci": { "collect": { "url": ["$URL"], "numberOfRuns": 2,
              "settings": { "extraHeaders": { "User-Agent": "$UA", "Accept-Language": "en-AU,en;q=0.9" } } } } }
          JSON

      - name: Lighthouse (desktop)
        run: lhci autorun --config=lighthouserc.json --collect.settings.preset=desktop --upload.target=temporary-public-storage

      - name: Lighthouse (mobile)
        run: lhci autorun --config=lighthouserc.json --collect.settings.preset=mobile --upload.target=temporary-public-storage
