name: WP code checks
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dev tools (PHPCS + WPCS)
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPCS (WordPress standard)
        run: composer run lint
