name: WP code checks
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install dev tools
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Auto-fix with PHPCBF
        run: |
          vendor/bin/phpcbf --standard=phpcs.xml || true

      - name: Commit auto-fixes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "style: phpcbf auto fixes [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHPCS and save report
        id: phpcs_run
        run: |
          vendor/bin/phpcs -s \
            --standard=phpcs.xml \
            --report=full \
            --report-file=phpcs-report.txt || echo "result=fail" >> $GITHUB_OUTPUT

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpcs-report
          path: phpcs-report.txt
          if-no-files-found: ignore

      - name: Fail if violations remain
        if: steps.phpcs_run.outputs.result == 'fail'
        run: exit 1
